Capitalize categories in export
findologic/dokuwiki-plugin-findologic-xml-export pull request #25
Opened 2017-10-09 09:28 UTC by TheKeymaster

2017-10-09 09:30 UTC, TheKeymaster commented
@georgms could you review this please?

2017-10-10 11:15 UTC, georgms requested changes

2017-10-10 11:15 UTC, georgms commented on _test/export.response.test.php
> +            'one' => ['home', 'Home'],
Nice test coverage! 1, 2, many.

Underscores are replaced with spaces. I see no test case for this. Unless I am missing something please add test cases for this; probably also mixed with colons replaced by underscore.

2017-10-10 14:44 UTC, TheKeymaster commented
@georgms I added two more test cases. With colons and underscores should work fine.

2017-10-11 12:13 UTC, merged