v1.3.0
findologic/dokuwiki-plugin-findologic-xml-export pull request #42
Opened 2018-02-05 12:42 UTC by TheKeymaster

2018-02-05 15:10 UTC, TheKeymaster commented
@georgms I have done a few things. First up:

 * If this PR is merged we do have :boom:  :boom:  :boom:  **100% Code Coverage** :boom:  :boom:  :boom: 
 * Tests take longer because some tests were not running properly before.
 * Missing tests were added to get this Code Coverage.

TODO NOW:

 * Automated test management.

2018-02-05 15:32 UTC, TheKeymaster commented
@georgms could you provide me a `GITHUB OAUTH TOKEN` for this repository?  
It must have the `public_repo` or `repo` scope to upload assets and please make sure it is encrypted ;).

2018-02-06 17:11 UTC, georgms commented
@TheKeymaster Please provide info on how to generate the OAuth token.

2018-02-06 17:11 UTC, georgms requested changes

2018-02-06 17:11 UTC, georgms commented on _test/template.response.test.php
> +        $this->assertEquals($adminCanAccessAswell, $adminPlugin->forAdminOnly());
`assertTrue`

2018-02-08 08:29 UTC, TheKeymaster commented
@georgms OAuth tokens can be generated in [Personal Access Tokens](https://github.com/settings/tokens). Please send me this token via mail, because it would require much things to install etc. in order to encrypt the API Key. I already got those things installed, so that's the easier way.

2018-02-08 09:59 UTC, georgms commented
@TheKeymaster I don't feel comfortable giving you my **personal** access token. Are you sure this is the right way to go?

2018-02-08 11:55 UTC, TheKeymaster commented
@georgms you don't need to. You can encrypt your key via the Travis command line tool, which is a ruby gem by yourself. Please follow these steps if you want to do so:

### If you do not have ruby

#### Installing ruby version manager (rvm)

```bash
> sudo apt-get --assume-yes update  
> command curl -sSL https://rvm.io/mpapis.asc | gpg --import -  
> curl -L https://get.rvm.io | bash -s stable  
> source ~/.rvm/scripts/rvm  
```

#### Installing ruby with rvm

```bash
> rvm install 2.3.0  
> rvm use 2.3.0 --default  
> ruby -v  
```

`ruby -v` to check if the installed version matches.

### If you do not have ruby-dev or gem

#### Installing ruby-dev and gem

```bash
> sudo apt-get install ruby2.3-dev
> sudo apt-get install gem
```

### Installing travis gem

```bash
> gem install travis
```

If you can't execute `travis`, then you might need to reboot your computer or re-login again.

### Encrypt your OAuth key

See [Encryption keys](https://docs.travis-ci.com/user/encryption-keys/).

2018-02-13 13:25 UTC, closed without merging

2018-02-13 13:32 UTC, TheKeymaster commented
See #44